DATASET:
  NAME: 'cityscapes'
  ROOT: 'datasets/cityscapes/'
  MODE: 'RGBD'
  N_CLASSES: 19
  CITYSCAPES:
    TRAIN_SET: 'train'
    GT_MODE: 'gtFine'

TRAIN:
  CHECKNAME: 'cityscapes_rgbd_xception_coco_fine'
  EPOCHS: 200
  FINETUNE: True

CHECKPOINT:
  DIRECTORY: 'models/resnet_coco_rgbd_2020_04_24/'
  MODEL: 'checkpoint.pth.tar'

MODEL:
  BACKBONE: 'xception'