DATASET:
  NAME: 'cityscapes'
  ROOT: 'datasets/cityscapes/'
  MODE: 'RGBD'
  SYNTHETIC: True
  N_CLASSES: 19

TRAIN:
  CHECKNAME: 'cityscapes_synth_rgbd_xception_fine_coarse'
  EPOCHS: 200
  FINETUNE: True

CHECKPOINT:
  DIRECTORY: 'run/cityscapes/cityscapes_synth_rgbd_xception_fine/'
  MODEL: 'model_best.pth.tar'

MODEL:
  BACKBONE: 'xception'