DATASET:
  NAME: 'cityscapes'
  ROOT: 'datasets/cityscapes/'
  MODE: 'RGB_HHA'
  N_CLASSES: 19

TRAIN:
  CHECKNAME: 'cityscapes_hha_imagenet'
  EPOCHS: 200

MODEL:
  INPUT_CHANNELS: 3
  BACKBONE_ZOO: True
