DATASET:
  NAME: 'cityscapes'
  ROOT: 'datasets/cityscapes/'
  MODE: 'RGB'
  N_CLASSES: 19

TRAIN:
  CHECKNAME: 'cityscapes_rgb_xception_scenenet'
  EPOCHS: 200
  FINETUNE: True

MODEL:
  INPUT_CHANNELS: 3
  BACKBONE: 'xception'

CHECKPOINT:
  DIRECTORY: 'models/run/scenenet/scenenet_rgbd_xception/2020_09_17-22_10_19/'
  MODEL: 'checkpoint.pth.tar'
  EXCLUDE: ['decoder.last_conv.8.weight', 'decoder.last_conv.8.bias']

