DATASET:
  NAME: 'cityscapes'
  ROOT: 'datasets/cityscapes/'
  MODE: 'RGBD'
  N_CLASSES: 19
  CITYSCAPES:
    TRAIN_SET: 'train'
    GT_MODE: 'gtFine'

TRAIN:
  CHECKNAME: 'cityscapes_rgbd_xception'
  EPOCHS: 200
  FINETUNE: True
  RESUME: True

RESUME:
  DIRECTORY: 'runs/cityscapes_rgbd_xception/'
  MODEL: 'model_best.pth.tar'

MODEL:
  BACKBONE: 'xception'