DATASET:
  NAME: 'cityscapes'
  ROOT: 'datasets/cityscapes/'
  MODE: 'RGB_HHA'
  N_CLASSES: 19
  CITYSCAPES:
    DEPTH_DIR: 'HHA'

TRAIN:
  CHECKNAME: 'cityscapes_midfusion_xception'
  EPOCHS: 200

MODEL:
  BACKBONE: 'xception'
  NAME: 'midfusion'
  INPUT_CHANNELS: 3
  BACKBONE_ZOO: True
  ASPP_DOUBLE: True
  DECODER_DOUBLE: True
