DATASET:
  NAME: 'cityscapes'
  ROOT: 'datasets/cityscapes/'
  MODE: 'RGBD'
  SYNTHETIC: True
  N_CLASSES: 19
  CITYSCAPES:
    DEPTH_DIR: 'VNL_Monocular'
    TRAIN_SET: 'train'
    GT_MODE: 'gtFine'

TRAIN:
  CHECKNAME: 'cityscapes_synth_rgbd_xception'
  EPOCHS: 200
  FINETUNE: True
  RESUME: True

RESUME:
  DIRECTORY: 'runs/cityscapes_synth_rgbd_xception/'
  MODEL: 'model_best.pth.tar'

MODEL:
  BACKBONE: 'xception'