DATASET:
  NAME: 'cityscapes'
  ROOT: 'datasets/cityscapes/'
  MODE: 'RGBD'
  N_CLASSES: 19

TRAIN:
  CHECKNAME: 'cityscapes_rgbd_xception_scenenet'
  EPOCHS: 200
  FINETUNE: True

MODEL:
  BACKBONE: 'xception'

CHECKPOINT:
  DIRECTORY: 'models/run/scenenet/scenenet_rgb_xception/2020_09_17-22_14_43/'
  MODEL: 'checkpoint.pth.tar'
  EXCLUDE: ['decoder.last_conv.8.weight', 'decoder.last_conv.8.bias']

