DATASET:
  NAME: 'coco'
  ROOT: 'datasets/coco/'
  MODE: 'RGB'
  COCO:
    CATEGORIES: 'coco'
  DARKEN: True

TRAIN:
  CHECKNAME: 'coco_xception'
  EPOCHS: 200

MODEL:
  INPUT_CHANNELS: 3
  BACKBONE_ZOO: True
  BACKBONE: 'xception'

