DATASET:
  NAME: 'scenenet'
  ROOT: 'datasets/scenenet'
  MODE: 'RGB'
  N_CLASSES: 14

TRAIN:
  CHECKNAME: 'scenenet_rgb_xception'
  EPOCHS: 200
  VAL_MAX: 1000
  EVAL_INTERVAL: 0.2

MODEL:
  BACKBONE: 'xception'
  INPUT_CHANNELS: 3

