DATASET:
  NAME: 'cityscapes'
  ROOT: 'datasets/cityscapes/'
  MODE: 'RGBD'
  N_CLASSES: 19

TRAIN:
  CHECKNAME: 'cityscapes_depthaware_coarse'
  EPOCHS: 200

MODEL:
  BACKBONE: 'depthaware_resnet'


