DATASET:
  NAME: 'cityscapes'
  ROOT: 'datasets/cityscapes/'
  USE_DEPTH: False
  N_CLASSES: 19

TRAIN:
  CHECKNAME: 'cityscapes_rgb_imagenet'
  EPOCHS: 100

MODEL:
  INPUT_CHANNELS: 3
  BACKBONE_ZOO: True
