DATASET:
  NAME: 'cityscapes'
  ROOT: 'datasets/cityscapes/'
  MODE: 'RGBD'
  SYNTHETIC: True
  N_CLASSES: 19
  CITYSCAPES:
    DEPTH_DIR: 'VNL_Monocular'

TRAIN:
  CHECKNAME: 'cityscapes_synth_rgbd_resnet'
  EPOCHS: 200