DATASET:
  NAME: 'coco'
  ROOT: 'datasets/coco/'
  MODE: 'RGB'
  COCO:
    CATEGORIES: 'pascal'
  N_CLASSES: 21

MODEL:
  INPUT_CHANNELS: 3
  BACKBONE_ZOO: True

TRAIN:
  CHECKNAME: 'coco_rgb_resnet_pt'
  EPOCHS: 100
  RESUME: 'pretrained/deeplab-resnet.pth.tar'