DATASET:
  NAME: 'cityscapes'
  ROOT: 'datasets/cityscapes/'
  MODE: 'RGB'
  N_CLASSES: 19
  DARKEN: True

TRAIN:
  CHECKNAME: 'cityscapes_rgb_xception_low_light'
  EPOCHS: 200

MODEL:
  BACKBONE: 'xception'
  INPUT_CHANNELS: 3