DATASET:
  NAME: 'cityscapes'
  ROOT: 'datasets/cityscapes/'
  MODE: 'RGBD'
  N_CLASSES: 19
  DARKEN:
    DARKEN: True

TRAIN:
  CHECKNAME: 'cityscapes_rgbd_depthaware_low_light'
  EPOCHS: 200

MODEL:
  BACKBONE: 'depthaware_resnet'