DATASET:
  NAME: 'scenenet'
  ROOT: 'datasets/scenenet'
  MODE: 'RGBD'
  N_CLASSES: 14
  DARKEN: True

TRAIN:
  CHECKNAME: 'scenenet_depthaware_lowlight'
  EPOCHS: 200
  VAL_MAX: 1000
  EVAL_INTERVAL: 0.2

MODEL:
  BACKBONE: 'depthaware_resnet'